### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#13]
Design visual checkpoints that give feedback to the player when activated.
It would be best that they have their own level. 
We can even add a few messages to the player on the wall during those ones such as "You can do it", "Don´t give up yet" or "Finally you made it here.."

**Comment by eg-ayoub** [comment]
Added level restart on damage.
Note: scene loading is way too fast to add a readable message. I can add an artificial timeout on the load of each level in order to show the message + display the transition animation.
