### ISSUE TITLE
Doors

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#19]
- [x]  Door states : closed / open.
~~Door sound effect~~ (#38, make separate issues about audio as it has its own implementation process)
- [x] design for the key.

**Comment by houss1evengames** [comment]
Design for the key is done

**Comment by houss1evengames** [comment]
pending : flames and skull animations.

**Comment by eg-ayoub** [comment]
are we keeping the same design for doors ? 
what about the spec ? 
I can start implementing doors now.

**Comment by houss1evengames** [comment]
@eg-ayoub you can start implementing the doors. 
They have the same design, the only difference is that the door goes from "closed" to "open" when the player collects the key.

**Comment by eg-ayoub** [comment]
doors are implemented. Need to put the animations in to close issue.
