### ISSUE TITLE
Pause menu 

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#2]
- remake of the pause menu as follow : resume game / retry level / quit game.
- add an option to turn on/off the music

**Comment by eg-ayoub** [comment]
@houss1evengames  please add a schematic.
if the retry option is in the menu, do we still need to have it as a shortcut? (holding a button)

**Comment by houss1evengames** [comment]
No we don't have to have it as a shortcut anymore. 
Pause menu should go as follow :

RESUME GAME
RETRY LEVEL
QUI GAME 

These elements will be displayed in a small black box that I will design later.
