### ISSUE TITLE
Title screen sprites

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#20]
- [x] Foreground 
- [x] Background 
- [x] Moving grass
- [x] Mansion

related to #1

**Comment by eg-ayoub** [comment]
Will we have parallax ?

**Comment by houss1evengames** [comment]
No need for parallax in my opinion,
Maybe could be implemented later in the polish

**Comment by houss1evengames** [comment]
Given how the title screen turned, I now think that a parallax could be a good idea

@eg-ayoub

**Comment by houss1evengames** [comment]
All sprites and assets are done, Only thing left is the level construction in Unity
