### ISSUE TITLE
Pumpkine

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#21]
Design + animation

**Comment by houss1evengames** [comment]
Design is done, the animation will be done straight in unity because of its simplicity.
I am going to need help to implement it in the Mansion DE.

**Comment by houss1evengames** [comment]
Design and animation done.
Mechanic left to implement

**Comment by eg-ayoub** [comment]
mechanic is implemented. 
Need to resize the sprite (way too big) and add bounce animation.
