### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by eg-ayoub** [eg-ayoub/TheMansionDE#22]
Import a first version of the player, with following mechanics:
- movement
- animations
Related to : #18
@houss1evengames  : If you add issues related to the the movement mechanics improvements, please relate them to this issue.

**Comment by eg-ayoub** [comment]
Is the dash to be implemented ? 
what about the jump on wall movement behavior ?

**Comment by houss1evengames** [comment]
No need for dash.
Wall jump (as well as the double jump) should have the same behaviour as the jump in my opinion. This is debatable.

@mrtheshotgunner97  I suggest a quick replay of the original game for a better perspective.

**Comment by eg-ayoub** [comment]
First version was implanted into the codebase.
what we need so far: 

- [ ] Tinker with physics and movement values (@houss1evengames )
- [x] Add control system (@mrtheshotgunner97)
- [ ] append animations and build animator graph (@mrtheshotgunner97  @houss1evengames )
