### ISSUE TITLE
Make UI system

### ISSUE THREAD

**Issue by eg-ayoub** [eg-ayoub/TheMansionDE#25]
a new UI system has to be made.
HUD might display : 
- [x] hearts (HP)
- [x] key status
- [x] level number
- [ ] save status
- [x] timer
- more ? 
Pause menu will be implemented later on.
Assets needed so far : 
- HP
- key
Related to: #2, #20, #8.

**Comment by houss1evengames** [comment]
- collectibles counter
- timer

**Comment by eg-ayoub** [comment]
some new specs for the new UI:
- HP displays as a set of UI Images that are render or not depending on the amount of HP.
- Level is a UI Text that shows the level ID.
- Key status is a UI Image that renders or not depending on whether the key status is taken or not

@houss1evengames  you can suggest a layout for the HUD.

**Comment by houss1evengames** [comment]
Same layout as original mansion with the key indicator underneath the HP and the level indicator in the middle at the top

**Comment by eg-ayoub** [comment]
maybe move other indicators (save / key / timer) to topright corner ?

**Comment by houss1evengames** [comment]
Yes Timer topright corner, save bottom right corner (i’ll make an animation)

**Comment by eg-ayoub** [comment]
@houss1evengames what about the key ?

**Comment by houss1evengames** [comment]
key indicator underneath hp, aligned to the left. mentioned in the comm just earlier mustn't have seen it

**Comment by houss1evengames** [comment]
Why is this issue closed but save status isn´t done ? @eg-ayoub
