### ISSUE TITLE
Art

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#28]
- [x] candles and chandelier 
- [x] windows to outside
- [x] various paintings 
- [x]  spider webs (for spider levels) 
- [x] spikes

**Comment by eg-ayoub** [comment]
The paintings seem like a nice idea. Maybe a story that unites the child and the mansion ? this is exciting !

**Comment by houss1evengames** [comment]
*meeting on friday (?) for further discussion about the story. @eg-ayoub confirm ?

**Comment by eg-ayoub** [comment]
friday night confirmed.
