### ISSUE TITLE
Control mapping

### ISSUE THREAD

**Issue by eg-ayoub** [eg-ayoub/TheMansionDE#29]
Here is a spec suggestion for the new controller mapping:

| Action | Keyboard        | Xbox One | DualShock 4 |
| --------- | ------------------ | ------------- | ----------------- |
| Jump   | spacebar        |       A        |        Cross     |
| Move   | direction keys |  left stick  |     left stick     |
| reset    |          R           |       Y        |       Triangle   |
| pause  |         Escape   |     Menu   |      Options     |

I am aiming for a seemless controller detection where mappings are switched automatically depending on the available controllers.

**Comment by houss1evengames** [comment]
mobile controls ?
suggestion (as per last talk) : 
- left analog for movement.
- right button for jump.
- pause for retry level.
