### ISSUE TITLE
Input when start level

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#3]
Starting the level, the player keeps executing last action. Means if he dies jumping, he respawns jumping ...
This could be fixed by introducing a *press to spawn player* as suggested in #1 . The animation could be the door opening and the character appearing, or just a pouf with some dust (zelda wind waker style)

**Comment by mrtheshotgunner97** [comment]
Related: #1

**Comment by houss1evengames** [comment]
This is what I referred to during last meeting

**Comment by eg-ayoub** [comment]
fixed in #35 eg-ayoub@a194709d81bc53185ea89158b1bec28a5b214452.
