### ISSUE TITLE
Portals 

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#30]
- [x] new design.
- [x] animation ( idle + on trigger ).
- [x] implement the mechanic.

related to #18

**Comment by eg-ayoub** [comment]
idea : maybe we can implement a "warping" animation that triggers on the player when hitting a portal ?

**Comment by houss1evengames** [comment]
Yes I am down

**Comment by eg-ayoub** [comment]
too late to make the warping animation.
Will implement in next commit.
Can I have the sprites for those?
