### ISSUE TITLE
Ghosts

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#31]
- [x] new design.
- [x] animation ( idle + follow ).
- [x] implement in the game.

related to #18

**Comment by eg-ayoub** [comment]
what about AI ?

**Comment by houss1evengames** [comment]
Constantly follows the player and tries to collide with. 
~~I propose speed slows a bit when he gets closer to the player~~

**Comment by houss1evengames** [comment]
~~Ignore last ligne of last comment~~
