### ISSUE TITLE
Spiders

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#32]
- [x] new design.
- [x] animation 
- [x] implement in the game.

related to #18

**Comment by eg-ayoub** [comment]
what about AI ?

**Comment by houss1evengames** [comment]
change the spider to larva 
- ramping enemy with specific movement trajectory. Used to make the platforms vanish and add a layer of complexity and intensity to the levels.

**Comment by eg-ayoub** [comment]
what does ramping mean ?
