### ISSUE TITLE
Loading animations

### ISSUE THREAD

**Issue by eg-ayoub** [eg-ayoub/TheMansionDE#35]
animations have three states : Fade In, Interim, and Fade out
While fade in and fade out are self explanatory, the Interim state is where all the loading happens,
it is where we can display a message on screen. I imagine it to be a plain black screen but we can have images or other media displayed.
In order to describe a good spec, I would need keyframes (sketches will be enough).
The animations to implement are: (so far)

- [x]  level restart
- [x]  return to checkpoint
- [x]  next level 

Related to: #15, #16

**Comment by houss1evengames** [comment]
I am not a 100% sure about what is meant by animations. 
Are we talking about transitions or small looping loading animations ?

Better we discuss this in order for me to be completely fixed about it.

**Comment by eg-ayoub** [comment]
I am talking about the transitions. 
the small looping clips can be part of those.

**Comment by houss1evengames** [comment]
next level fade in animation completed.

**Comment by houss1evengames** [comment]
next level fade out animation completed.
