### ISSUE TITLE
Saving and checkpoints

### ISSUE THREAD

**Issue by eg-ayoub** [eg-ayoub/TheMansionDE#36]
This is a master issue (closed all related)
![Drawing](https://user-images.githubusercontent.com/20781976/67233487-94ec2180-f443-11e9-9979-bea97664ee06.png)
this shows how the save system works:
- timer will track time until next checkpoint is reached, then reset. (ex: levels 1 through 4 inclusive)
- checkpoints save the state AFTER their level is finished. (ex: you only save between level 4 and 5)
- the saving is done during the level transition 

Related to: #13, #7 , #6

**Comment by eg-ayoub** [comment]
values to be saved: 

~~index of the checkpoint~~

- [x]  times so far

~~number of hearts~~

**Comment by houss1evengames** [comment]
![ECF6D30D-AC85-4941-A354-89F18FE7FE6A](https://user-images.githubusercontent.com/51530352/67337582-9a229c80-f527-11e9-9f29-a920d1ff3f76.png)

**Comment by eg-ayoub** [comment]
The save system has an enum : 
`enum CHECKPOINTS {NONE=0, FIRST, SECOND, THIRD ....}`
a value of this enum is given to each scene to specify if it is a checkpoint scene or not (and its index)
the save file comes in a JSON format : 
`{ "SaveHealth": <hp>, "SaveTimes": [ <t1>, <t2> ...], "SaveCandies": <candies> }`
saving is done during scene transition. 
we also keep a constant for the total number of checkpoints. (for conveniency)

**Comment by houss1evengames** [comment]
![9FA04744-91D4-41B7-9ACA-756F7C631768](https://user-images.githubusercontent.com/51530352/67389881-caa41e00-f59b-11e9-89fb-0b2b9626fae7.png)
![4D79B965-93C3-4E94-B62A-AD531BDFB057](https://user-images.githubusercontent.com/51530352/67389883-cb3cb480-f59b-11e9-8a95-3e8e9a38eb79.jpeg)

- visual approach to the hud area
- checkpoint doors, mansion of madness to the right

**Comment by eg-ayoub** [comment]
Checkpoints and saving has been fully implemented
