### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#38]
!!REVIEW ALL AUDIOS AND SFX. COULD BE A LOT BETTER!!

- [x] Music
- [x] Player (landing, death, run,)
- [x] Ghostoon - Looping Directional 
- [x] Crawler - Looping Directional
- [x] Game over
- [x] Door open 
- [x] Lava - Directional 
- [x] Portals warp - Directional.
- [x] key
- [x] Collectibles

**Comment by houss1evengames** [comment]
Music only on levels.
Title screen and hub will have ambiant sounds

**Comment by houss1evengames** [comment]
The grand piano in the area to the left of the entrance should be playing the music for the hub/title screen. 
@eg-ayoub it would be nice if the player could turn it off and on by somehow interacting with the piano.

**Comment by houss1evengames** [comment]
Portal Idle sound effects will be deleted because it is way too annoying/disturbing for the player.

**Comment by eg-ayoub** [comment]
We can also make those sounds directional, or only have sounds on warp.

**Comment by houss1evengames** [comment]
Yes, we keep warp only. 
Directional sfx wouldn't fix the problem.

**Comment by houss1evengames** [comment]
All sound effects should be reviewed and/or changed. 
Sound effects that need change will be unchecked from the list.
