### ISSUE TITLE
Spider path 

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#4]
Change the way we define the path for the spider.
The problem is that the spider stops when one of the platforms to which it was supposed to go to disappears, thus making some levels not work the way intended.

**Comment by eg-ayoub** [comment]
Dynamic path finding would take time.
I suggest we redesign the spider.

**Comment by houss1evengames** [comment]
I agree. 
We can design something else, doesn't even have to be a spider.
Should I close this issue and open a new one ?

**Comment by eg-ayoub** [comment]
issue closed.
