### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#41]
There are three themes : 

- solo piano that plays in the HUB. Source : the piano in the credits area. ( #39 )
- the mansion original theme - played inside the playable levels.
- the mansion of madness theme - played inside the mansion of madness levels.

 Related to #38

**Comment by eg-ayoub** [comment]
main theme and hubWorld are done. closing issue. 
All mansion of madness things will be treated in another project.
