### ISSUE TITLE
Spawn bug on deaths/retry

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#47]
**Description**
The player spawns at the spawn point but stays immobile, not even going down. No control is available at that moment. When that happens, the retry button stops working as well. 
However you can still pause and quit the game.

This is noticed in the build mac OSX 1.0.0 and affects all levels except level one.

_This bug only happens in the build version and does not seem to happen at all in unity_

**How to reproduce**
Reload the level (die or retry) twice in a row ( at least twice, given the fact that I was never able to reload the level more than two times.

<img width="1680" alt="Capture d’écran 2019-11-02 à 10 45 27" src="https://user-images.githubusercontent.com/51530352/68069584-3a679500-fd62-11e9-9068-218277e8c7bd.png">

**Comment by eg-ayoub** [comment]
I cannot debug this yet as I don't have my hands on the build.
