### ISSUE TITLE
Replay levels

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#8]
An option could be that the player could go back to any chosen checkpoints to play the game from there (on condition the CP was already reached before), and the option to replay any level chosen if the player finishes the game.

**Comment by houss1evengames** [comment]
The solution to this issue is adressed in #36.
Permission to clsoe this issue ?

**Comment by eg-ayoub** [comment]
Level replay is now a natural result of the hub world layout.
