### ISSUE TITLE
Mansion of madness

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#9]
- [x] Draw mirror frame.
- [ ] Design level 1/2
- [ ] Design level 2/2

- [ ] add particles to mansion of madness area in hub.

- [ ] add BUZZSAWS.

NB. collect key at half the length of the level.

**Comment by eg-ayoub** [comment]
are the mansion of madness levels individual levels by door ?

**Comment by houss1evengames** [comment]
No. They are levels that work the same way as the original mansion game : played one after the other. If game over you have to redo the mansion of madness from the start.

**Comment by houss1evengames** [comment]
This will be added later on to a new version of The Mansion. 
This issue will be closed now.

**Comment by houss1evengames** [comment]
QUESTION @eg-ayoub - Is it possible to have a (different) specific number of max HPs for Mansion of Madness only ? 
For example, the actual number of hearts is 4, is it possible to upgrade it to 8 when in Mansion of Madness ?

**Comment by houss1evengames** [comment]
This issue is no longer relevant. Need a new issue for Mansion of Madness.
Closing.
